### PR TITLE
VPython labextension support on remote host.

### PR DESCRIPTION
**Pull request by jcoady**
Made changes to enable the vpython labextension to work with JupyterLab running on a remote host such as binder or JupyterHub.

### CODE REVIEW

**Comment by jcoady** [comment]
Hi Matt

   This failed on the Mac build but I only changed 1 line of code in the vpython file with_notebook.py . The other file changes had to do with the vpython labextension which I don't think are part of your build. I think you were working on fixing a Mac build issue with a different pull request and that problem is why this build failed.

John

**Comment by mwcraig** [comment]
I'm going to see if I can reproduce the mac problem tonight.

**Comment by mwcraig** [comment]
Well, I can make the problem happen on my local mac. No idea *why* it happens yet. What was odd about this is that there wasn't any change in our code that brought this on, so I'm going to check to see if there were some recent conda releases that broke something.

**Comment by mwcraig** [comment]
@jcoady -- I just merged a fix for the test failure (there is something wrong with python 3.7.4 from conda and with conda build 3.8.10 so I'm using earlier versions of each).

Can you rebase this to pull in the latest changes?

If you haven't rebased before or want me to do the rebase and push it to your branch please let me know.

**Comment by jcoady** [comment]
Hi Matt, 
 
   Can you perform the rebase for me and push it to my branch.

Thanks

**Comment by mwcraig** [comment]
Hi John,

I just did the tense and pushed it.

Matt

**Comment by jcoady** [comment]
Thanks Matt

**Pull request merged**
